// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: catalog/v2/catalog.proto

package catalogv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProductStatus int32

const (
	ProductStatus_PRODUCT_STATUS_UNSPECIFIED ProductStatus = 0
	ProductStatus_PRODUCT_STATUS_ACTIVE      ProductStatus = 1
	ProductStatus_PRODUCT_STATUS_ARCHIVED    ProductStatus = 2
)

// Enum value maps for ProductStatus.
var (
	ProductStatus_name = map[int32]string{
		0: "PRODUCT_STATUS_UNSPECIFIED",
		1: "PRODUCT_STATUS_ACTIVE",
		2: "PRODUCT_STATUS_ARCHIVED",
	}
	ProductStatus_value = map[string]int32{
		"PRODUCT_STATUS_UNSPECIFIED": 0,
		"PRODUCT_STATUS_ACTIVE":      1,
		"PRODUCT_STATUS_ARCHIVED":    2,
	}
)

func (x ProductStatus) Enum() *ProductStatus {
	p := new(ProductStatus)
	*p = x
	return p
}

func (x ProductStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProductStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_catalog_v2_catalog_proto_enumTypes[0].Descriptor()
}

func (ProductStatus) Type() protoreflect.EnumType {
	return &file_catalog_v2_catalog_proto_enumTypes[0]
}

func (x ProductStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProductStatus.Descriptor instead.
func (ProductStatus) EnumDescriptor() ([]byte, []int) {
	return file_catalog_v2_catalog_proto_rawDescGZIP(), []int{0}
}

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PriceCents    int64                  `protobuf:"varint,3,opt,name=price_cents,json=priceCents,proto3" json:"price_cents,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Status        ProductStatus          `protobuf:"varint,6,opt,name=status,proto3,enum=catalog.v2.ProductStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_catalog_v2_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v2_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_catalog_v2_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetPriceCents() int64 {
	if x != nil {
		return x.PriceCents
	}
	return 0
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Product) GetStatus() ProductStatus {
	if x != nil {
		return x.Status
	}
	return ProductStatus_PRODUCT_STATUS_UNSPECIFIED
}

type GetProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRequest) Reset() {
	*x = GetProductRequest{}
	mi := &file_catalog_v2_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRequest) ProtoMessage() {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v2_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v2_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *GetProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductResponse) Reset() {
	*x = GetProductResponse{}
	mi := &file_catalog_v2_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductResponse) ProtoMessage() {}

func (x *GetProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v2_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductResponse.ProtoReflect.Descriptor instead.
func (*GetProductResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v2_catalog_proto_rawDescGZIP(), []int{2}
}

func (x *GetProductResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type ListProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsRequest) Reset() {
	*x = ListProductsRequest{}
	mi := &file_catalog_v2_catalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsRequest) ProtoMessage() {}

func (x *ListProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v2_catalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsRequest.ProtoReflect.Descriptor instead.
func (*ListProductsRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v2_catalog_proto_rawDescGZIP(), []int{3}
}

func (x *ListProductsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListProductsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsResponse) Reset() {
	*x = ListProductsResponse{}
	mi := &file_catalog_v2_catalog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsResponse) ProtoMessage() {}

func (x *ListProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v2_catalog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsResponse.ProtoReflect.Descriptor instead.
func (*ListProductsResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v2_catalog_proto_rawDescGZIP(), []int{4}
}

func (x *ListProductsResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *ListProductsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_catalog_v2_catalog_proto protoreflect.FileDescriptor

const file_catalog_v2_catalog_proto_rawDesc = "" +
	"\n" +
	"\x18catalog/v2/catalog.proto\x12\n" +
	"catalog.v2\"\xb7\x01\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vprice_cents\x18\x03 \x01(\x03R\n" +
	"priceCents\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x121\n" +
	"\x06status\x18\x06 \x01(\x0e2\x19.catalog.v2.ProductStatusR\x06status\"#\n" +
	"\x11GetProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"C\n" +
	"\x12GetProductResponse\x12-\n" +
	"\aproduct\x18\x01 \x01(\v2\x13.catalog.v2.ProductR\aproduct\"Q\n" +
	"\x13ListProductsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"o\n" +
	"\x14ListProductsResponse\x12/\n" +
	"\bproducts\x18\x01 \x03(\v2\x13.catalog.v2.ProductR\bproducts\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken*g\n" +
	"\rProductStatus\x12\x1e\n" +
	"\x1aPRODUCT_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PRODUCT_STATUS_ACTIVE\x10\x01\x12\x1b\n" +
	"\x17PRODUCT_STATUS_ARCHIVED\x10\x022\xb0\x01\n" +
	"\x0eCatalogService\x12K\n" +
	"\n" +
	"GetProduct\x12\x1d.catalog.v2.GetProductRequest\x1a\x1e.catalog.v2.GetProductResponse\x12Q\n" +
	"\fListProducts\x12\x1f.catalog.v2.ListProductsRequest\x1a .catalog.v2.ListProductsResponseBRZPgithub.com/LeeDark/go-microservices-starter/grpc-playground/catalog/v2;catalogv2b\x06proto3"

var (
	file_catalog_v2_catalog_proto_rawDescOnce sync.Once
	file_catalog_v2_catalog_proto_rawDescData []byte
)

func file_catalog_v2_catalog_proto_rawDescGZIP() []byte {
	file_catalog_v2_catalog_proto_rawDescOnce.Do(func() {
		file_catalog_v2_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_v2_catalog_proto_rawDesc), len(file_catalog_v2_catalog_proto_rawDesc)))
	})
	return file_catalog_v2_catalog_proto_rawDescData
}

var file_catalog_v2_catalog_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_catalog_v2_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_catalog_v2_catalog_proto_goTypes = []any{
	(ProductStatus)(0),           // 0: catalog.v2.ProductStatus
	(*Product)(nil),              // 1: catalog.v2.Product
	(*GetProductRequest)(nil),    // 2: catalog.v2.GetProductRequest
	(*GetProductResponse)(nil),   // 3: catalog.v2.GetProductResponse
	(*ListProductsRequest)(nil),  // 4: catalog.v2.ListProductsRequest
	(*ListProductsResponse)(nil), // 5: catalog.v2.ListProductsResponse
}
var file_catalog_v2_catalog_proto_depIdxs = []int32{
	0, // 0: catalog.v2.Product.status:type_name -> catalog.v2.ProductStatus
	1, // 1: catalog.v2.GetProductResponse.product:type_name -> catalog.v2.Product
	1, // 2: catalog.v2.ListProductsResponse.products:type_name -> catalog.v2.Product
	2, // 3: catalog.v2.CatalogService.GetProduct:input_type -> catalog.v2.GetProductRequest
	4, // 4: catalog.v2.CatalogService.ListProducts:input_type -> catalog.v2.ListProductsRequest
	3, // 5: catalog.v2.CatalogService.GetProduct:output_type -> catalog.v2.GetProductResponse
	5, // 6: catalog.v2.CatalogService.ListProducts:output_type -> catalog.v2.ListProductsResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_catalog_v2_catalog_proto_init() }
func file_catalog_v2_catalog_proto_init() {
	if File_catalog_v2_catalog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_v2_catalog_proto_rawDesc), len(file_catalog_v2_catalog_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_catalog_v2_catalog_proto_goTypes,
		DependencyIndexes: file_catalog_v2_catalog_proto_depIdxs,
		EnumInfos:         file_catalog_v2_catalog_proto_enumTypes,
		MessageInfos:      file_catalog_v2_catalog_proto_msgTypes,
	}.Build()
	File_catalog_v2_catalog_proto = out.File
	file_catalog_v2_catalog_proto_goTypes = nil
	file_catalog_v2_catalog_proto_depIdxs = nil
}
